spring:
  profiles:
    active: default

security:
  basic:
    enabled: false
  require-ssl: true

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}
        key-alias: ${keystoreSSLKey:tomcat}

